# Generated by Django 5.2.13 on 2026-04-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='secret',
            field=models.CharField(max_length=255),
        ),
    ]
